FROM mcr.microsoft.com/dotnet/sdk:9.0-preview AS build

WORKDIR /src

COPY /src/Wisdom.sln .
COPY /src/WebApp ./WebApp/

WORKDIR /src/WebApp
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0-preview AS runtime
WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080
ENTRYPOINT ["dotnet", "WebApp.dll"]