services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached      
    network_mode: service:db
    command: sleep infinity

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dbadmin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'pwd'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'pwd'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - widsom_db:/var/lib/mysql
  # Names our volume
volumes:
  wisdom_db: